perturbations = [
    "Tell the story out of chronological order using flashbacks and dreams.",
    "Begin the story in the middle of an exciting event to grab attention.",
    "Use a story within a story, where a character tells a tale to others.",
    "Tell the story starting from the end and moving backward to the beginning.",
    "Have a narrator who misunderstands events, revealing the truth as the story unfolds.",
    "End the story where it began, showing the characters' journey coming full circle.",
    "Tell two related stories side by side that connect at the end.",
    "Present the story in pieces that the reader assembles as they read.",
    "Write the story using 'you' to make the reader the main character.",
    "Tell the story through letters, diary entries, or messages.",
    "Let an animal or object narrate the story from their perspective.",
    "Narrate the story from a group's point of view, like a family or team.",
    "Swap the usual roles of characters, like making the sidekick the hero.",
    "Include an object that seems important but turns out to be a distraction.",
    "Have the character relive the same day until they learn a lesson.",
    "Include a 'bad' character who has good intentions.",
    "Have a character who forgets who they are and discovers it during the story.",
    "Set the story in a small world that represents bigger ideas.",
    "Use the setting to symbolize the character's emotions or journey.",
    "Have the setting itself act like a character with feelings.",
    "Let the characters talk directly to the reader.",
    "Include technology that affects the characters in interesting ways.",
    "Have the character discover something they're not supposed to know.",
    "Include situations that seem contradictory but reveal a truth.",
    "Place contrasting elements side by side to highlight differences.",
    "Jump forward in time to show how things change.",
    "Have a character grow younger as the story progresses.",
    "Include a time limit to add excitement to the story.",
    "Personify time as a character who interacts with others.",
    "Use moments of silence or pauses to create mood or emphasis.",
    "Describe things using senses in unusual ways, like 'hearing colors' or 'tasting sunshine'.",
    "Include a time-travel element where characters visit the past or future.",
    "Have characters switch bodies or identities and learn from each other's lives.",
    "Create a story where characters have to solve riddles or puzzles to advance.",
    "Introduce a character who speaks in rhyme or riddles.",
    "Set the story in a world where time moves differently.",
    "Include a character who can communicate with the environment, like talking to trees or rivers.",
    "Have the story take place in a world where everyone has forgotten something important, and the characters try to rediscover it.",
    "Create a story where music or art plays a central role in solving a problem.",
    "Include an imaginary friend who turns out to be real.",
    "Write a story that incorporates elements from different cultures or myths.",
    "Let characters experience events from different perspectives, like seeing the same event through different eyes.",
    "Use paradoxes in the story, like a character who can only speak the truth but tells a lie.",
    "Set the story in a place where things are the opposite of what they seem.",
    "Have a character who can see into the future but must decide whether to change it.",
    "Use sensory language to describe emotions, like 'her happiness tasted like sweet strawberries.'",
    "Include friendly monsters or creatures that challenge stereotypes.",
    "Introduce a character who can shape-shift or change forms."
]